Skeleton start
Baseline11/resident pull request #25
Opened 2022-04-22 15:45 UTC by mohsin2596

2022-04-22 21:02 UTC, mohsin2596 commented
@matejthetree the navigation isnt working right now ... will debug in morning but would wanna hear some comments on the structure laid out from you and @matheus7mm 

One thing I gotta point out is that without a cli or a plugin of our own it seems like too much boilerplate configuration

2022-04-23 07:17 UTC, matejthetree commented on modules/login_module/lib/riverflow/command/login_command.dart
> +    //Todo: Add call to auth service here and update login state
shall we be listening to stream of auth service, then that listener will call a command of its own to update the store. else if it is only manually, like this is good. 

if stream, then you only call auth service over here.

2022-04-23 07:17 UTC, matejthetree commented on modules/login_module/lib/riverflow/signal/login_signal.dart
> +// Todo: Try without payload. Store to hold these values instead
you will always have payload, either on form updated or on login.

if on form updated, it populates store inside the module. 

if we keep no state inside the for outside of the widget, the payload goes in login.

in first case the login command would read the data from loginForm store and pass it to the auth service

2022-04-23 07:17 UTC, matejthetree commented on modules/login_module/lib/riverflow/signal/login_signal.dart
> +class LoginUserPayload {
every payload freezed

2022-04-23 07:17 UTC, matejthetree commented on modules/login_module/lib/src/ui/login_module_widget.dart
> +    return ModuleWidget(
make navigator 2 here as well. later we think how to do it inside module widget.

2022-04-23 07:17 UTC, matejthetree commented on modules/root/lib/riverflow/user/store/user_store.dart
> +  void login({required bool isLoggedIn}) {
this would be called updateLoginState or smth. login has different meaning

2022-04-23 21:25 UTC, mohsin2596 commented on modules/login_module/lib/src/ui/login_module_widget.dart
> +    return ModuleWidget(
@matejthetree makes sense ... cuz here we could add forgot password and signup etc as the other pages

2022-04-24 07:39 UTC, matejthetree requested changes

2022-04-24 07:39 UTC, matejthetree commented on lib/main.dart
> +                    if (ref.watch(userObservableProvider).isLoggedIn)
this is a little bit clunky, consumer should be inside the root module and based on observable it should return just builder with with observable as parametar. then we can implement splash screen inside with time. main function should not have consumer.

you can also ask in root module constructor for 2 builders, loggedInBuilder and loggedOutBuilder, and then create navigation inside with both pages, and in init state when observable changes you navigate to the flow, or push and pop to the second one. if it is first run, it is splash page for 2 seconds

2022-04-24 07:39 UTC, matejthetree commented on modules/root/lib/src/ui/root_module_widget.dart
> +class RootModule extends StatelessWidget {
hide the code of the module behind the src, and just export store and observable

2022-04-24 07:39 UTC, matejthetree commented on modules/root/lib/riverflow/user/store/user_store.dart
> +  void updateUserState({required bool isLoggedIn}) {
updateUserLoginState

2022-04-24 23:43 UTC, mohsin2596 commented on lib/main.dart
> +                    if (ref.watch(userObservableProvider).isLoggedIn)
Root now asks for two widgets for loggedIn and loggedOut states, the builder inside root returns a consumer listening to user state switching between the two widget types. Each widget has their own Navigator. Going to see a better way to have Splash screen where we bootstrap stuff

2022-04-24 23:47 UTC, mohsin2596 commented on modules/root/lib/src/ui/root_module_widget.dart
> +class RootModule extends StatelessWidget {
But we need the widget inside of main.dart so cant hide it

2022-04-25 17:04 UTC, matejthetree requested changes

2022-04-25 17:04 UTC, matejthetree commented on modules/root/lib/riverflow/user/store/user_store.dart
> +class UserStore extends BaseStore {
eventually stores will be big so we will have SubStores. just a class that is initialized under this store. more for pretty stuff.

it can update observables and dispatch signals, but it will not be mapped or provider, main store will have API for substores

2022-04-25 17:04 UTC, matejthetree commented on modules/root/lib/src/ui/root_module_widget.dart
> +              ? (isLoggedIn ? loggedInNavigator : loggedOutNavigator)
`bootstrapComplete ? bootstrapCompleteBuilder(context, isLoggedIn) : BootstrapModule()`

inside main bootstrapBuilder

`builder (context, isLoggedIn) : isLoggedIn ? HomeModule () : LoginModule();`

2022-04-25 17:04 UTC, matejthetree commented on modules/root/lib/src/ui/splash/splash_page.dart
> +    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
where are my hooks :D

2022-04-25 17:31 UTC, mohsin2596 commented on modules/root/lib/riverflow/bootstrap/observable/bootstrap_observable.freezed.dart
> +  bool get bootstrapComplete => throw _privateConstructorUsedError;
Good point ... ill add them in git ignore

2022-04-25 17:33 UTC, mohsin2596 commented on modules/root/lib/src/ui/root_module_widget.dart
> +              ? (isLoggedIn ? loggedInNavigator : loggedOutNavigator)
@matejthetree Bootstrap module here is too much duplication for a very small use case ... gotta setup pubspecs separately etc etc. It is also something that would not be used outside of rootmodule. What do ya say?

2022-04-25 17:35 UTC, mohsin2596 commented on modules/resident_home_module/lib/src/ui/resident_home_module_widget.dart
> +    return ModuleWidget(
@matejthetree we can but the one confusion I have is that each navigator would be switching state based on individual logics ... unless we decide to have a navigation observable which holds the state of which page we are suppose to be on.

2022-04-25 17:35 UTC, mohsin2596 commented on lib/navigators/logged_in_navigator.dart
> +Navigator loggedInNavigator() {
ill try to refactor it further

2022-04-26 09:08 UTC, mohsin2596 commented on modules/resident_home_module/lib/src/ui/resident_home_module_widget.dart
> +    return ModuleWidget(
Will test in login flow branch

2022-04-26 09:09 UTC, merged

2022-04-26 09:50 UTC, matejthetree commented
makes sense

On Mon, Apr 25, 2022, 7:33 PM Muhammad Mohsin Ajmal <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In modules/root/lib/src/ui/root_module_widget.dart
> <https://github.com/Baseline11/resident/pull/25#discussion_r857868403>:
>
> > +      required this.loggedOutNavigator,
> +      required this.providerContainer})
> +      : super(key: key);
> +
> +  @override
> +  Widget build(BuildContext context) {
> +    return ModuleWidget(
> +      configure: () => providerContainer,
> +      builder: (_) => Consumer(builder: (_, ref, __) {
> +        final bootstrapComplete =
> +            ref.watch(bootstrapObservableProvider).bootstrapComplete;
> +        final isLoggedIn = ref.watch(userObservableProvider).isLoggedIn;
> +
> +        return MaterialApp(
> +          home: bootstrapComplete
> +              ? (isLoggedIn ? loggedInNavigator : loggedOutNavigator)
>
> @matejthetree <https://github.com/matejthetree> Bootstrap module here is
> too much duplication for a very small use case ... gotta setup pubspecs
> separately etc etc. It is also something that would not be used outside of
> rootmodule. What do ya say?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Baseline11/resident/pull/25#discussion_r857868403>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMX5ISLTDA6GHV5MMW7GFTVG3JPPANCNFSM5UCWJJ5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>